<?php /*a:2:{s:66:"D:\wwwroot\cesyx01.cn\application\admin\view\users\level_list.html";i:1583903732;s:54:"D:\wwwroot\cesyx01.cn\application\admin\view\main.html";i:1575947686;}*/ ?>
<div class="layui-card layui-bg-gray"><?php if(!(empty($title) || (($title instanceof \think\Collection || $title instanceof \think\Paginator ) && $title->isEmpty()))): ?><div class="layui-card-header layui-anim layui-anim-fadein notselect"><span class="layui-icon layui-icon-next font-s10 color-desc margin-right-5"></span><?php echo htmlentities((isset($title) && ($title !== '')?$title:'')); ?><div class="pull-right"><?php if(auth("add_level")): ?><button data-modal='<?php echo url("add_level"); ?>' data-title="添加会员等级" class='layui-btn'>添加会员等级</button><?php endif; ?></div></div><?php endif; ?><div class="layui-card-body layui-anim layui-anim-upbit"><div class="think-box-shadow"><table class="layui-table margin-top-15" lay-filter="tab" lay-skin="line"><?php if(!(empty($list) || (($list instanceof \think\Collection || $list instanceof \think\Paginator ) && $list->isEmpty()))): ?><thead><tr><th lay-data="{field:'name'}" class='text-left nowrap'>会员等级名称</th><th lay-data="{field:'level'}" class='text-left nowrap'>刷单数</th><th lay-data="{field:'status'}" class='text-left nowrap'>等级状态</th><th lay-data="{field:'edit',width:130,fixed: 'right'}" class='text-left nowrap'>操作</th></tr></thead><?php endif; ?><tbody><?php foreach($list as $key=>$vo): ?><tr><td class='text-left nowrap'><?php echo htmlentities($vo['name']); ?></td><td class='text-left nowrap'><?php echo htmlentities($vo['order_num']); ?></td><td class='text-center nowrap'><?php if($vo['status'] == '2'): ?><span class="color-red">已禁用</span><?php else: ?><span class="color-green">使用中</span><?php endif; ?></td><td class='text-left nowrap'><?php if(auth("edit_level")): ?><a data-dbclick class="layui-btn layui-btn-xs" data-title="编辑菜单" data-modal='<?php echo url("admin/users/edit_level"); ?>?id=<?php echo htmlentities($vo['id']); ?>'>编 辑</a><?php endif; if(($vo['status'] == 1) and auth("edit_level_status")): ?><a class="layui-btn layui-btn-xs layui-btn-warm" data-csrf="<?php echo systoken('admin/users/edit_level_status'); ?>" data-action="<?php echo url('edit_level_status',['status'=>2,'id'=>$vo['id']]); ?>" data-value="id#<?php echo htmlentities($vo['id']); ?>;status#2" style='background:red;'>禁用</a><?php elseif(($vo['status'] == 2) and auth("edit_level_status")): ?><a class="layui-btn layui-btn-xs layui-btn-warm" data-csrf="<?php echo systoken('admin/users/edit_level_status'); ?>" data-action="<?php echo url('edit_level_status',['status'=>1,'id'=>$vo['id']]); ?>" data-value="id#<?php echo htmlentities($vo['id']); ?>;status#1" style='background:green;'>启用</a><?php endif; ?></td></tr><?php endforeach; ?></tbody></table><script>        var table = layui.table;
        //转换静态表格
        var limit = Number('<?php echo htmlentities(app('request')->get('limit')); ?>');
        if(limit==0) limit=20;
        table.init('tab', {
                cellMinWidth:120,
                skin: 'line,row',
                size: 'lg',
                limit: limit
            }); 
    </script><?php if(empty($list) || (($list instanceof \think\Collection || $list instanceof \think\Paginator ) && $list->isEmpty())): ?><span class="notdata">没有记录哦</span><?php else: ?><?php echo (isset($pagehtml) && ($pagehtml !== '')?$pagehtml:''); ?><?php endif; ?></div></div></div>